### PR TITLE
WalletConnect web3-provider added

### PR DESCRIPTION
**Pull request by leirbag95**
When a user wants to connect with his wallet, a modal appears and offers him 2 ways to connect:
- Metamask
- Wallet Connect

If the user chooses metamask, the schema remains the same, the metamask popup appears and asks him to connect an account.

If Wallet Connect is selected, a QR Code dedicated to the connection appears.

To learn more about the API, I used the official documentation

https://docs.walletconnect.com/quick-start/dapps/web3-provider

Code snippet

```
const wc = new WalletConnectProvider({
  infuraId: this.infura_key,
  qrcodeModalOptions: {
    mobileLinks: [
      'metamask',
      'trust'
     ]
})
```

### CODE REVIEW

**Comment by hoh** [comment]
@BjrInt can you review this PR ?

**Review by BjrInt — APPROVED** [review]

**Comment by BjrInt** [comment]
Maybe just an observation: 
Metamask is not the only available wallet (ex: Brave's default wallet), wouldn't it be more thorough to rename the "Metamask" button to "default wallet" ?

**Comment by leirbag95** [comment]
We should leave Metamask because for the moment we only integrate it as a wallet (without taking into account Wallet connect). Brave's wallet connects in the same way as metamask but not all other wallets.
Moreover most of the dapps (uniswap, sushiswap, curve finance ...) use the term metamask in their UI, we should keep this. If a user wants to interact with another compatible wallet he will use wallet connect or we will add new wallet as we go along.

**Comment by hoh** [comment]
@leirbag95 can you solve the conflicts ?

**Pull request merged**
